app = "inhouse-e4"
primary_region = "ams"

[build]

[env]
  PORT = "8080"

# Persistent volume for the SQLite database.
[[mounts]]
  source      = "sqlite_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https   = true
  auto_stop_machines  = false
  auto_start_machines = true

  [[http_service.checks]]
    grace_period  = "5s"
    interval      = "30s"
    method        = "GET"
    path          = "/"
    timeout       = "5s"
